FROM harbor-cz.deepblueai.com/cuda/ubuntu16.04-nocuda-automl

MAINTAINER WangJin <wangjin@deepblueai.com>


# Install your python pkg
RUN pip install --no-cache-dir opencv-python


# Install your train code

# COPY . /tmp/


# edit your entrypoint

# ENTRYPOINT ["python", "/tmp/${your code dir ...}/*.py"]